# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binary_repr <- function(x) {
    .Call('_pryr_binary_repr', PACKAGE = 'pryr', x)
}

hex_repr <- function(x) {
    .Call('_pryr_hex_repr', PACKAGE = 'pryr', x)
}

binary2hex <- function(x) {
    .Call('_pryr_binary2hex', PACKAGE = 'pryr', x)
}

inspect_ <- function(x, base_env) {
    .Call('_pryr_inspect_', PACKAGE = 'pryr', x, base_env)
}

address2 <- function(name, env) {
    .Call('_pryr_address2', PACKAGE = 'pryr', name, env)
}

named2 <- function(name, env) {
    .Call('_pryr_named2', PACKAGE = 'pryr', name, env)
}

v_size <- function(n, size) {
    .Call('_pryr_v_size', PACKAGE = 'pryr', n, size)
}

object_sizes <- function(objects, base_env) {
    .Call('_pryr_object_sizes', PACKAGE = 'pryr', objects, base_env)
}

object_size_ <- function(x, base_env) {
    .Call('_pryr_object_size_', PACKAGE = 'pryr', x, base_env)
}

is_promise2 <- function(name, env) {
    .Call('_pryr_is_promise2', PACKAGE = 'pryr', name, env)
}

promise_code <- function(name, env) {
    .Call('_pryr_promise_code', PACKAGE = 'pryr', name, env)
}

promise_value <- function(name, env) {
    .Call('_pryr_promise_value', PACKAGE = 'pryr', name, env)
}

promise_evaled <- function(name, env) {
    .Call('_pryr_promise_evaled', PACKAGE = 'pryr', name, env)
}

promise_env <- function(name, env) {
    .Call('_pryr_promise_env', PACKAGE = 'pryr', name, env)
}

makeExplicit <- function(prom) {
    .Call('_pryr_makeExplicit', PACKAGE = 'pryr', prom)
}

explicitPromise <- function(name, env) {
    .Call('_pryr_explicitPromise', PACKAGE = 'pryr', name, env)
}

explicitDots <- function(env) {
    .Call('_pryr_explicitDots', PACKAGE = 'pryr', env)
}

slice <- function(x, k, sep = " ") {
    .Call('_pryr_slice', PACKAGE = 'pryr', x, k, sep)
}

#' @export
#' @rdname inspect
sexp_type <- function(x) {
    .Call('_pryr_sexp_type', PACKAGE = 'pryr', x)
}

typename2 <- function(name, env) {
    .Call('_pryr_typename2', PACKAGE = 'pryr', name, env)
}

