# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_promise2 <- function(name, env) {
    .Call('pryr_is_promise2', PACKAGE = 'pryr', name, env)
}

promise_code <- function(name, env) {
    .Call('pryr_promise_code', PACKAGE = 'pryr', name, env)
}

promise_value <- function(name, env) {
    .Call('pryr_promise_value', PACKAGE = 'pryr', name, env)
}

promise_evaled <- function(name, env) {
    .Call('pryr_promise_evaled', PACKAGE = 'pryr', name, env)
}

promise_env <- function(name, env) {
    .Call('pryr_promise_env', PACKAGE = 'pryr', name, env)
}

